//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroup
    {
        public decimal AcGrp_Key { get; set; }
        public string AcGrp_GrpName { get; set; }
        public Nullable<decimal> AcGrp_grpId { get; set; }
        public string AcGrp_Desc { get; set; }
        public string AcGrp_Type { get; set; }
    }
}
