//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountHeads_Mst
    {
        public double AhMst_Key { get; set; }
        public string AhMst_pName { get; set; }
        public Nullable<decimal> AhMst_OpBal { get; set; }
        public string AhMst_OpStatus { get; set; }
        public Nullable<decimal> AhMst_CrLimit { get; set; }
        public string AhMst_Tin { get; set; }
        public string AhMst_Ismale { get; set; }
        public string AhMst_drEdDet { get; set; }
        public Nullable<double> AhMst_SplID { get; set; }
        public string AhMst_Address { get; set; }
        public Nullable<double> AhMst_AreaID { get; set; }
        public string AhMst_ContPrsn { get; set; }
        public string AhMst_Phno { get; set; }
        public string AhMst_mobile { get; set; }
        public Nullable<double> AhMst_HosId { get; set; }
        public Nullable<System.DateTime> AhMst_Dob { get; set; }
        public Nullable<System.DateTime> AhMst_WedAnn { get; set; }
        public string AhMst_Email { get; set; }
        public Nullable<int> AhMst_SendMail { get; set; }
        public Nullable<int> AhMst_IsActive { get; set; }
        public string AhMst_Note { get; set; }
        public string AhMst_IssDate { get; set; }
        public Nullable<int> AhMst_IsCrdHldr { get; set; }
        public string AhMst_Type { get; set; }
        public string AhMst_AcGrpId { get; set; }
        public Nullable<double> AhMst_DiscPer { get; set; }
        public Nullable<decimal> AhMst_SchemeId { get; set; }
        public string AhMst_DrCode { get; set; }
        public Nullable<int> AhMst_IsEmp { get; set; }
        public Nullable<int> AhMst_IsDocBod { get; set; }
        public Nullable<int> AhMst_IsDocWedng { get; set; }
        public string AhMst_Landmark { get; set; }
        public string AhMst_PatientPerDay { get; set; }
        public Nullable<double> AhMst_RegFee { get; set; }
        public Nullable<decimal> AhMst_CustTypeId { get; set; }
        public string AhMst_PayType { get; set; }
        public byte[] AhMst_Image { get; set; }
        public Nullable<double> AhMst_TstDiscPer { get; set; }
        public Nullable<int> AhMst_CatgryId { get; set; }
        public string AhMst_HospAddress { get; set; }
        public string AhMst_HospName { get; set; }
        public string AhMst_DefltAddress { get; set; }
        public string AhMst_PRO { get; set; }
        public string AhMst_OthrNote { get; set; }
        public Nullable<int> AhMst_CRDays { get; set; }
        public Nullable<int> AhMst_Incen { get; set; }
        public string LEVEL1 { get; set; }
        public string GROUPLEVEL { get; set; }
        public string GROUPCODE { get; set; }
        public string AhMst_NationalID { get; set; }
        public string AhMst_PassPortNo { get; set; }
        public string Ahmst_Code { get; set; }
        public Nullable<bool> AhMst_IsLettHd { get; set; }
        public string AhMst_DefPaymode { get; set; }
        public string AhMst_VistAddress { get; set; }
        public string AhMst_ConsltTime { get; set; }
        public string AhMst_ConsltTime2 { get; set; }
        public string AhMst_Docimage { get; set; }
        public Nullable<bool> AhMst_IsDiscPat { get; set; }
        public Nullable<int> AhMst_AvdSms { get; set; }
    }
}
