//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baranches_Mst
    {
        public double BrMst_Key { get; set; }
        public string BrMst_Code { get; set; }
        public string BrMst_Name { get; set; }
        public string BrMst_Address1 { get; set; }
        public string BrMst_Address2 { get; set; }
        public string BrMst_Address3 { get; set; }
        public string BrMst_Place { get; set; }
        public Nullable<int> BrMst_SchemeId { get; set; }
        public string BrMst_UserInfo { get; set; }
        public Nullable<int> BrMst_IsActive { get; set; }
        public string BrMst_Theme { get; set; }
        public byte[] BrMst_logo { get; set; }
        public Nullable<int> BrMst_IsCollCen { get; set; }
        public Nullable<int> BrMst_IsSubColl { get; set; }
        public string BrMst_smsTxt { get; set; }
        public string BrMst_BillWiseCollSms { get; set; }
        public string BrMst_SmsBillTxt { get; set; }
        public Nullable<int> BrMst_IsAvoid { get; set; }
        public Nullable<int> BrMst_UniqId { get; set; }
        public string BrMst_RsltUrl { get; set; }
        public Nullable<int> BrMst_PayTransfBrnch { get; set; }
        public Nullable<int> BrMst_PayTransfFrom { get; set; }
        public Nullable<int> BrMst_PayTransfTo { get; set; }
        public string BrMst_Email { get; set; }
        public string BrMst_IcmrNo { get; set; }
        public string BrMst_DisplayName { get; set; }
        public string BrMst_WebUrl { get; set; }
        public Nullable<int> BrMst_TstPrfmSchemeid { get; set; }
        public string BrMst_ReqSMS { get; set; }
        public string BrMst_LisfyUrl { get; set; }
        public Nullable<bool> BrMst_IsLisfy { get; set; }
        public Nullable<bool> BrMst_EnbLbRequest { get; set; }
        public Nullable<int> BrMst_IsWeb { get; set; }
        public Nullable<bool> BrMst_IsCorpBillSMS { get; set; }
        public string BrMst_WhatsAppText { get; set; }
        public string BrMst_UpdLocPath { get; set; }
    }
}
