//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillWiseCollection
    {
        public decimal BlWsCol_Key { get; set; }
        public Nullable<int> BlWsCol_CorpId { get; set; }
        public Nullable<decimal> BlWsCol_VchrKey { get; set; }
        public Nullable<int> BlWsCol_InvNo { get; set; }
        public Nullable<System.DateTime> BlWsCol_Date { get; set; }
        public Nullable<double> BlWsCol_AlloAmt { get; set; }
        public Nullable<double> BlWsCol_CurBal { get; set; }
        public Nullable<int> BlWsCol_YearId { get; set; }
        public Nullable<int> BlWsCol_CompanyId { get; set; }
        public string BlWsCol_UserInfo { get; set; }
        public Nullable<int> BlWsCol_BrId { get; set; }
        public Nullable<int> BlWsCol_Status { get; set; }
        public string BlWsCol_CancelInfo { get; set; }
        public Nullable<decimal> BlWsCol_EntryKey { get; set; }
    }
}
