//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashClosing_UserWise
    {
        public decimal UsrCash_Key { get; set; }
        public Nullable<decimal> UsrCash_CclKey { get; set; }
        public Nullable<decimal> UsrCash_TransNo { get; set; }
        public string UsrCash_Name { get; set; }
        public Nullable<double> UsrCash_Amount { get; set; }
        public string UsrCash_Type { get; set; }
        public Nullable<decimal> UsrCash_User { get; set; }
        public Nullable<int> UsrCash_UsrId { get; set; }
        public Nullable<int> UsrCash_YrId { get; set; }
        public Nullable<int> UsrCash_CpyId { get; set; }
        public Nullable<int> UsrCash_InvUserId { get; set; }
    }
}
