//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashClosing_Mst
    {
        public decimal Ccl_Key { get; set; }
        public Nullable<System.DateTime> Ccl_Date { get; set; }
        public string Ccl_Time { get; set; }
        public Nullable<double> Ccl_Coll1 { get; set; }
        public Nullable<double> Ccl_Coll2 { get; set; }
        public Nullable<double> Ccl_PayMnt { get; set; }
        public Nullable<double> Ccl_OffAmt { get; set; }
        public Nullable<double> Ccl_CshDen1000 { get; set; }
        public Nullable<double> Ccl_CshDen500 { get; set; }
        public Nullable<double> Ccl_CshDen100 { get; set; }
        public Nullable<double> Ccl_CshDen50 { get; set; }
        public Nullable<double> Ccl_CshDen20 { get; set; }
        public Nullable<double> Ccl_CshDen10 { get; set; }
        public Nullable<double> Ccl_CshDen5 { get; set; }
        public Nullable<double> Ccl_CshDenCoins { get; set; }
        public Nullable<double> Ccl_CshDenSum { get; set; }
        public string Ccl_Note { get; set; }
        public Nullable<double> Ccl_ToOffice { get; set; }
        public Nullable<double> Ccl_Balance { get; set; }
        public Nullable<double> Ccl_Short { get; set; }
        public Nullable<double> Ccl_Excess { get; set; }
        public string Ccl_Tmpstmp { get; set; }
        public Nullable<decimal> Ccl_UsrId { get; set; }
        public Nullable<decimal> Ccl_YrId { get; set; }
        public Nullable<decimal> Ccl_CpyId { get; set; }
        public Nullable<decimal> Ccl_Updtd { get; set; }
        public Nullable<double> Ccl_CshDen2000 { get; set; }
        public string Ccl_Description { get; set; }
        public Nullable<double> Ccl_Receipt { get; set; }
        public Nullable<double> Ccl_CshDen200 { get; set; }
    }
}
