//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customize2_RsltDescMst
    {
        public int Cust2Rslt_Key { get; set; }
        public int Cust2Rslt_TstId { get; set; }
        public string Cust2Rslt_Desc { get; set; }
    }
}
