//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenaralRslt_Det
    {
        public decimal GenRsltDet_Key { get; set; }
        public Nullable<double> GenRsltDet_LabNo { get; set; }
        public Nullable<double> GenRsltDet_TstID { get; set; }
        public string GenRsltDet_Nrml { get; set; }
        public string GenRsltDet_Result { get; set; }
        public Nullable<double> GenRsltDet_GrpId { get; set; }
        public Nullable<int> GenRsltDet_SH { get; set; }
        public Nullable<double> GenRsltDet_Orderby { get; set; }
        public string GenRsltDet_Note { get; set; }
        public string GenRsltDet_MstrNote { get; set; }
        public Nullable<System.DateTime> GenRsltDet_Dt { get; set; }
        public Nullable<decimal> GenRsltDet_RmvIfBlnk { get; set; }
        public string GenRsltDet_Usr { get; set; }
        public Nullable<decimal> GenRsltDet_UsrId { get; set; }
        public Nullable<decimal> GenRsltDet_YrId { get; set; }
        public Nullable<decimal> GenRsltDet_CpyId { get; set; }
        public Nullable<decimal> GenRsltDet_Updtd { get; set; }
        public string GenRsltDet_Unit { get; set; }
        public string GenRsltDet_Crtlow { get; set; }
        public string GenRsltDet_Crthigh { get; set; }
        public string GenRsltDet_UsrFirLeAut { get; set; }
        public Nullable<decimal> GenRsltDet_UsrIdFirLeAut { get; set; }
        public string GenRsltDet_UsrSecLeAut { get; set; }
        public Nullable<decimal> GenRsltDet_UsrIdSecLeAut { get; set; }
        public Nullable<decimal> GenRsltDet_CriticalStatus { get; set; }
        public string GenRsltDet_RsltOrgValue { get; set; }
        public Nullable<bool> GenRsltDet_Crtbold { get; set; }
        public string GenRsltDet_Tech { get; set; }
        public string GenRsltDet_Technology { get; set; }
        public string GenRsltDet_Method { get; set; }
        public string GenRsltDet_Specifcn { get; set; }
        public string GenRsltDet_AnlyzerName { get; set; }
        public Nullable<bool> GenRsltDet_BrUpdtd { get; set; }
        public Nullable<bool> GenRsltDet_IsBrRslt { get; set; }
        public string GenRsltDet_SyncInfo { get; set; }
    }
}
