//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public string CODE { get; set; }
        public string HEAD { get; set; }
        public string LEVEL1 { get; set; }
        public string GROUPLEVEL { get; set; }
        public string GROUPCODE { get; set; }
        public decimal BALANCE { get; set; }
        public decimal OPBALANCE { get; set; }
        public string LEGAL { get; set; }
        public string USERID { get; set; }
        public string PASS { get; set; }
    }
}
