//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntrfceMechine_1
    {
        public decimal IM1_key { get; set; }
        public Nullable<System.DateTime> IM1_InvDate { get; set; }
        public Nullable<decimal> IM1_InvNo { get; set; }
        public string IM1_RsltNo { get; set; }
        public string IM1_SmplId { get; set; }
        public Nullable<decimal> IM1_TstId { get; set; }
        public Nullable<decimal> IM1_MtstId { get; set; }
        public Nullable<decimal> IM1_TstGrpId { get; set; }
        public Nullable<decimal> IM1_TstType { get; set; }
        public string IM1_Rslt { get; set; }
        public string IM1_Rslt1 { get; set; }
        public Nullable<double> IM1_Rslt2 { get; set; }
        public string IM1_Normal { get; set; }
        public Nullable<decimal> IM1_Sh { get; set; }
        public Nullable<decimal> IM1_Orderby { get; set; }
        public string IM1_Name { get; set; }
        public string IM1_Gendr { get; set; }
        public string IM1_Age { get; set; }
        public string IM1_PhNo { get; set; }
        public string IM1_Ymd { get; set; }
        public Nullable<int> IM1_Updt { get; set; }
        public Nullable<decimal> IM1_CopyId { get; set; }
        public Nullable<decimal> IM1_YrId { get; set; }
        public string IM1_UsrInfo { get; set; }
        public Nullable<decimal> IM1_BrnchId { get; set; }
        public Nullable<int> IM1_SelType { get; set; }
        public string IM1_RsltNote { get; set; }
        public Nullable<System.DateTime> IM1_RsltDate { get; set; }
        public string IM1_Rslt_User { get; set; }
        public string IM1_Rslt_UserE { get; set; }
        public string IM1_Rslt_UserH { get; set; }
        public string IM1_Flg { get; set; }
        public Nullable<decimal> IM1_DeptId { get; set; }
        public Nullable<int> IM1_SplCltd { get; set; }
        public Nullable<System.DateTime> IM1_DateTime { get; set; }
        public string IM1_User { get; set; }
        public Nullable<System.DateTime> IM1_AtLab { get; set; }
        public string IM1_AtLabUsr { get; set; }
        public Nullable<int> IM1_Saved { get; set; }
        public Nullable<int> IM1_Authorized { get; set; }
        public Nullable<int> IM1_Pulled { get; set; }
        public string IM1_AuthByUsr { get; set; }
        public Nullable<System.DateTime> IM1_AuthDateTime { get; set; }
        public Nullable<bool> IM1_Authorize { get; set; }
        public Nullable<bool> IM1_AuthorizeHOD { get; set; }
        public Nullable<decimal> IM1_Nrml_Crtlow { get; set; }
        public Nullable<decimal> IM1_Nrml_Crthigh { get; set; }
        public Nullable<decimal> IM1_Nrml_Low { get; set; }
        public Nullable<decimal> IM1_Nrml_High { get; set; }
        public Nullable<decimal> IM1_TestPerformAt { get; set; }
        public Nullable<decimal> IM1_Updtd { get; set; }
        public Nullable<System.DateTime> IM1_ReportedOn { get; set; }
    }
}
