//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Det
    {
        public decimal InvItm_key { get; set; }
        public Nullable<double> InvItm_Invno { get; set; }
        public Nullable<double> InvItm_TstId { get; set; }
        public Nullable<double> InvItm_rate { get; set; }
        public Nullable<int> InvItm_Orgrate { get; set; }
        public Nullable<int> InvItm_Issued { get; set; }
        public string InvItm_SmplId { get; set; }
        public Nullable<int> InvItm_SmplStats { get; set; }
        public Nullable<decimal> InvItm_UsrId { get; set; }
        public Nullable<decimal> InvItm_YrId { get; set; }
        public Nullable<decimal> InvItm_CpyId { get; set; }
        public Nullable<decimal> InvItm_Updtd { get; set; }
        public Nullable<System.DateTime> InvItm_CutDateTime { get; set; }
        public string InvItm_CutUser { get; set; }
        public Nullable<int> InvItm_CutPaper { get; set; }
        public Nullable<decimal> InvItm_DiscPer { get; set; }
        public Nullable<int> InvItm_Type { get; set; }
        public Nullable<int> InvItm_DepId { get; set; }
        public string InvItm_CompletedUserInfo { get; set; }
        public string InvItm_SampledUser { get; set; }
        public Nullable<System.DateTime> InvItm_SampledOn { get; set; }
        public string InvItm_SampleModeId { get; set; }
        public Nullable<int> InvItm_IsPrinted { get; set; }
        public Nullable<double> InvItm_TstOrgRate { get; set; }
        public Nullable<double> InvItm_DiscAmt { get; set; }
        public Nullable<double> InvItm_RevDiscAmt { get; set; }
        public Nullable<int> InvItm_ScndLvl { get; set; }
        public Nullable<int> InvItm_Refrllab { get; set; }
    }
}
