//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Mst
    {
        public double Inv_No { get; set; }
        public Nullable<int> Inv_IsInsrnce { get; set; }
        public Nullable<double> Inv_PntId { get; set; }
        public Nullable<int> Inv_PntInvId { get; set; }
        public string Inv_PayMode { get; set; }
        public string Inv_Tittle { get; set; }
        public string Inv_name { get; set; }
        public string Inv_Gender { get; set; }
        public int Inv_age { get; set; }
        public string Inv_ageymd { get; set; }
        public string Inv_phno { get; set; }
        public string Inv_Address { get; set; }
        public Nullable<System.DateTime> Inv_SmplDate { get; set; }
        public string Inv_RsltNO { get; set; }
        public Nullable<double> Inv_BrID { get; set; }
        public Nullable<System.DateTime> Inv_Date { get; set; }
        public string Inv_time { get; set; }
        public Nullable<double> Inv_InsId { get; set; }
        public string Inv_InsNo { get; set; }
        public Nullable<double> Inv_AreaId { get; set; }
        public Nullable<int> Inv_EmailtoPatient { get; set; }
        public string Inv_Email { get; set; }
        public Nullable<int> Inv_EtoDr { get; set; }
        public Nullable<double> Inv_DrId { get; set; }
        public string Inv_OutDr { get; set; }
        public Nullable<double> Inv_hospId { get; set; }
        public Nullable<double> Inv_Schrge { get; set; }
        public Nullable<double> Inv_DiscId { get; set; }
        public Nullable<double> Inv_CltnID { get; set; }
        public Nullable<double> Invl_DiscPer { get; set; }
        public Nullable<System.DateTime> Inv_RepTime { get; set; }
        public Nullable<double> Inv_GrosAmt { get; set; }
        public Nullable<double> Inv_DiscAmt { get; set; }
        public Nullable<double> Inv_OthAmt { get; set; }
        public Nullable<double> Inv_Netamt { get; set; }
        public Nullable<double> Inv_RcvdAmt { get; set; }
        public Nullable<double> Inv_BalAmt { get; set; }
        public string Inv_Comment { get; set; }
        public string Inv_RptMode { get; set; }
        public Nullable<System.DateTime> Inv_CmpltdDate { get; set; }
        public string Inv_CmpltdTime { get; set; }
        public string Inv_OthCmnt { get; set; }
        public string Inv_User { get; set; }
        public Nullable<int> Invl_IsPending { get; set; }
        public Nullable<int> Inv_Status { get; set; }
        public string Inv_CnlComnt { get; set; }
        public string Inv_Cnltmestmp { get; set; }
        public Nullable<double> Inv_CurRcvdAmt { get; set; }
        public Nullable<double> Inv_CurBalAmt { get; set; }
        public Nullable<decimal> Inv_UsrId { get; set; }
        public decimal Inv_YrId { get; set; }
        public decimal Inv_CpyId { get; set; }
        public Nullable<decimal> Inv_Updtd { get; set; }
        public string Inv_ItemDesc { get; set; }
        public string Inv_SentMail { get; set; }
        public Nullable<bool> Inv_RepThrPersonal { get; set; }
        public Nullable<bool> Inv_RepThrCourier { get; set; }
        public Nullable<bool> Inv_RepThrPhone { get; set; }
        public Nullable<bool> Inv_RepThrEmail { get; set; }
        public Nullable<bool> Inv_RepThrSms { get; set; }
        public string Inv_DocPath1 { get; set; }
        public string Inv_DocPath2 { get; set; }
        public Nullable<decimal> Inv_CollModeId { get; set; }
        public string Inv_DocPath3 { get; set; }
        public string Inv_SampleStatus { get; set; }
        public Nullable<int> Inv_PrintCount { get; set; }
        public string Inv_ShortName { get; set; }
        public Nullable<double> Inv_Roundoff { get; set; }
        public Nullable<double> Inv_ItemDisc { get; set; }
        public Nullable<int> Inv_CashAllUsr { get; set; }
        public Nullable<int> Inv_CashUsr { get; set; }
        public Nullable<bool> Inv_WhatsApp { get; set; }
        public Nullable<bool> Inv_WhatsAppStatus { get; set; }
        public string Inv_WhatsAppUserInfo { get; set; }
        public Nullable<decimal> Inv_Token { get; set; }
        public string Inv_TokenValue { get; set; }
        public string Inv_Ward { get; set; }
        public Nullable<decimal> Inv_WardId { get; set; }
        public Nullable<int> Inv_InPackge { get; set; }
        public Nullable<int> Inv_PrintBillC { get; set; }
        public Nullable<int> Inv_ScanComplete { get; set; }
        public Nullable<double> Inv_RefundAmt { get; set; }
        public string Inv_Area { get; set; }
        public Nullable<bool> Inv_RevInc { get; set; }
        public string Inv_MemberCode { get; set; }
        public Nullable<System.DateTime> Inv_AuthDate { get; set; }
        public Nullable<System.DateTime> Inv_Horeceived { get; set; }
        public Nullable<int> Inv_PresChck { get; set; }
        public Nullable<int> Inv_AutoMail { get; set; }
        public string Inv_SRFno { get; set; }
        public string Inv_Passport { get; set; }
        public Nullable<int> Inv_ModalitDiv { get; set; }
        public Nullable<System.DateTime> Inv_SRFDate { get; set; }
        public string Inv_Specimn { get; set; }
        public Nullable<int> Inv_SpecimnId { get; set; }
        public Nullable<System.DateTime> Inv_Rcvddate { get; set; }
        public Nullable<System.DateTime> Inv_Rcvdtime { get; set; }
        public string Inv_Userinfo { get; set; }
        public string Inv_Mob { get; set; }
        public string Inv_MailError { get; set; }
        public string Inv_Aadhaar { get; set; }
        public Nullable<System.DateTime> Inv_Dob { get; set; }
        public string Inv_Nationality { get; set; }
        public Nullable<int> Inv_Hcbill { get; set; }
        public Nullable<int> Inv_CovidStatus { get; set; }
        public Nullable<bool> Inv_BrUpdtd { get; set; }
        public Nullable<bool> Inv_IsCorpReqBill { get; set; }
        public string Inv_WhatsAppError { get; set; }
        public string Inv_LisfyPath { get; set; }
        public Nullable<bool> Inv_LisfyUpdtd { get; set; }
        public string Inv_LisfyInfo { get; set; }
        public string Inv_Punchyth { get; set; }
        public string Inv_District { get; set; }
        public string Inv_LocalBody { get; set; }
        public string Inv_CountryCode { get; set; }
        public string Inv_SecMob { get; set; }
        public Nullable<int> Inv_BankId { get; set; }
        public Nullable<int> Inv_ageYY { get; set; }
        public Nullable<int> Inv_ageDD { get; set; }
        public Nullable<int> Inv_ageMM { get; set; }
        public Nullable<System.DateTime> Inv_MailTryedOn { get; set; }
        public Nullable<int> Inv_MailTryed { get; set; }
        public Nullable<int> Inv_IsNewPat { get; set; }
        public Nullable<int> Inv_UserLevel { get; set; }
    }
}
