//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labcor_Login
    {
        public int LabCorp_Id { get; set; }
        public string LabCorp_Name { get; set; }
        public string LabCorp_UserName { get; set; }
        public string LabCorp_Password { get; set; }
        public Nullable<int> LabCorp_CpyId { get; set; }
        public Nullable<int> LabCorp_BrId { get; set; }
        public int LabCorp_Key { get; set; }
        public Nullable<int> LabCorp_YrID { get; set; }
        public Nullable<bool> LabCorp_BlckAccnts { get; set; }
        public Nullable<bool> LabCorp_BlckInvce { get; set; }
        public string LabCorp_Theme { get; set; }
        public Nullable<bool> LabCorp_EnbLbRequest { get; set; }
    }
}
