//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public int Mstr_Key { get; set; }
        public string Mstr_Desc { get; set; }
        public string Mstr_Type { get; set; }
        public string Mstr_Code { get; set; }
        public string Mstr_Details { get; set; }
        public Nullable<double> Mstr_Value { get; set; }
    }
}
