//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalRanx
    {
        public double Nrml_Key { get; set; }
        public Nullable<double> Nrml_TstID { get; set; }
        public Nullable<double> Nrml_Agefr { get; set; }
        public string Nrml_Agetype { get; set; }
        public Nullable<double> Nrml_Ageto { get; set; }
        public string Nrml_Agetypeto { get; set; }
        public string Nrml_Sex { get; set; }
        public string Nrml_Norage { get; set; }
        public string Nrml_Low { get; set; }
        public string Nrml_Crtlow { get; set; }
        public string Nrml_High { get; set; }
        public string Nrml_Crthigh { get; set; }
    }
}
