//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opening_Balance
    {
        public int OpBl_Key { get; set; }
        public Nullable<int> OpBl_AccId { get; set; }
        public Nullable<double> OpBl_OpBalance { get; set; }
        public string OpBl_OpStatus { get; set; }
        public Nullable<double> OpBl_ClosingBal { get; set; }
        public Nullable<int> OpBl_UsrId { get; set; }
        public Nullable<int> OpBl_YrId { get; set; }
        public Nullable<int> OpBl_CpyId { get; set; }
        public string Head { get; set; }
    }
}
