//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Mst
    {
        public decimal Patient_Opdno { get; set; }
        public string Patient_Title { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<decimal> AhMst_OpBal { get; set; }
        public string AhMst_OpStatus { get; set; }
        public Nullable<decimal> AhMst_CrLimit { get; set; }
        public string AhMst_Tin { get; set; }
        public string Patient_Ismale { get; set; }
        public string AhMst_drEdDet { get; set; }
        public Nullable<double> AhMst_SplID { get; set; }
        public string Patient_Address { get; set; }
        public Nullable<double> AhMst_AreaID { get; set; }
        public string AhMst_ContPrsn { get; set; }
        public string Patient_Phno { get; set; }
        public string Patient_mobile { get; set; }
        public Nullable<double> AhMst_HosId { get; set; }
        public Nullable<System.DateTime> Patient_Dob { get; set; }
        public Nullable<System.DateTime> AhMst_WedAnn { get; set; }
        public string Patient_Email { get; set; }
        public int AhMst_SendMail { get; set; }
        public Nullable<int> AhMst_IsActive { get; set; }
        public string AhMst_Note { get; set; }
        public Nullable<System.DateTime> AhMst_IssDate { get; set; }
        public Nullable<int> AhMst_IsCrdHldr { get; set; }
        public string AhMst_Type { get; set; }
        public string AhMst_AcGrpId { get; set; }
        public Nullable<double> AhMst_DiscPer { get; set; }
        public Nullable<decimal> AhMst_SchemeId { get; set; }
        public Nullable<decimal> AhMst_MaxId { get; set; }
        public string Patient_Code { get; set; }
        public string AhMst_DrCode { get; set; }
        public Nullable<int> AhMst_IsEmp { get; set; }
        public Nullable<int> AhMst_IsDocBod { get; set; }
        public Nullable<int> AhMst_IsDocWedng { get; set; }
        public string AhMst_Landmark { get; set; }
        public string AhMst_PatientPerDay { get; set; }
        public Nullable<double> AhMst_RegFee { get; set; }
        public string AhMst_NationalID { get; set; }
        public string AhMst_PassPortNo { get; set; }
        public Nullable<decimal> AhMst_CpyId { get; set; }
        public string AhMst_Code { get; set; }
        public Nullable<double> AhMst_Key { get; set; }
        public string AhMst_pName { get; set; }
        public string AhMst_Address { get; set; }
        public string AhMst_mobile { get; set; }
        public Nullable<System.DateTime> AhMst_Dob { get; set; }
        public string AhMst_Phno { get; set; }
        public string AhMst_Email { get; set; }
        public string AhMst_Ismale { get; set; }
        public string AhMst_Prfx { get; set; }
    }
}
