//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingCollection
    {
        public double PndC_Key { get; set; }
        public Nullable<double> PndC_Labno { get; set; }
        public Nullable<System.DateTime> PndC_Date { get; set; }
        public Nullable<double> PndC_Amount { get; set; }
        public string PndC_TimeSmp { get; set; }
        public Nullable<int> PndC_Cancld { get; set; }
        public Nullable<decimal> PndC_UsrId { get; set; }
        public Nullable<decimal> PndC_YrId { get; set; }
        public Nullable<decimal> PndC_CpyId { get; set; }
        public Nullable<decimal> PndC_Updtd { get; set; }
        public string PndC_InvPaymode { get; set; }
        public Nullable<double> PndC_InsId { get; set; }
        public string PndC_InsNo { get; set; }
        public Nullable<int> PndC_CashAllUsr { get; set; }
        public Nullable<int> PndC_CashUsr { get; set; }
    }
}
