//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Dispatching
    {
        public double RptDis_Key { get; set; }
        public Nullable<double> RptDis_LabNo { get; set; }
        public string RptDis_Dispmode { get; set; }
        public string RptDis_Userinfo { get; set; }
        public string RptDis_Note { get; set; }
        public Nullable<decimal> RptDis_UsrId { get; set; }
        public Nullable<decimal> RptDis_YrId { get; set; }
        public Nullable<decimal> RptDis_CpyId { get; set; }
        public string RptDis_Person { get; set; }
    }
}
