//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_GroupTest
    {
        public decimal StGrpTst_Key { get; set; }
        public Nullable<int> StGrpTst_GrpId { get; set; }
        public Nullable<int> StGrpTst_TstCode { get; set; }
        public Nullable<int> StGrpTst_OrderBy { get; set; }
        public int StGrpTst_Sh { get; set; }
    }
}
