//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_UserRightSel
    {
        public int UsrSel_Key { get; set; }
        public Nullable<int> UsrSel_UsrId { get; set; }
        public string UsrSel_MainMenu { get; set; }
        public string UsrSel_SubMenu { get; set; }
        public string UsrSel_MenuName { get; set; }
        public Nullable<bool> UsrSel_Select { get; set; }
        public Nullable<int> UsrSel_Orderby { get; set; }
    }
}
