//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_UserRights
    {
        public int Usr_Key { get; set; }
        public string Usr_MainMenu { get; set; }
        public string Usr_SubMenu { get; set; }
        public string Usr_MenuName { get; set; }
        public Nullable<bool> Usr_Select { get; set; }
        public Nullable<int> Usr_Orderby { get; set; }
        public Nullable<int> Usr_Admin { get; set; }
        public Nullable<int> Usr_Super { get; set; }
        public Nullable<int> Usr_Staff { get; set; }
    }
}
