//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetDoctor_Staff
    {
        public double SetCorp_Key { get; set; }
        public Nullable<decimal> SetCorp_StaffId { get; set; }
        public decimal SetCorp_CorpId { get; set; }
        public string SetCorp_UserInfo { get; set; }
    }
}
