//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING
    {
        public int StgID { get; set; }
        public string StgGroup { get; set; }
        public string StgCode { get; set; }
        public string StgDesc { get; set; }
        public string StgDetails { get; set; }
        public string StgValue { get; set; }
        public Nullable<int> StgModiUserID { get; set; }
        public Nullable<System.DateTime> StgModiDate { get; set; }
        public Nullable<int> StgcmpID { get; set; }
        public Nullable<int> StgbrnID { get; set; }
        public Nullable<int> StgFinYearID { get; set; }
    }
}
