//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special_SchemeRates
    {
        public decimal SplSchR_Key { get; set; }
        public Nullable<decimal> SplSchR_ID { get; set; }
        public Nullable<double> SplSchR_NRate { get; set; }
        public Nullable<decimal> SplSchR_TstID { get; set; }
        public Nullable<double> SplSchR_DisPer { get; set; }
    }
}
