//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special_Rates
    {
        public decimal SplR_Key { get; set; }
        public Nullable<int> SplR_ID { get; set; }
        public Nullable<decimal> SplR_NRate { get; set; }
        public Nullable<int> SplR_TstID { get; set; }
        public Nullable<double> SplR_DisPer { get; set; }
    }
}
