//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRef_Mst
    {
        public decimal TestRef_Key { get; set; }
        public Nullable<decimal> TestRef_Id { get; set; }
        public string TestRef_RefName { get; set; }
        public Nullable<double> TestRef_SpRate { get; set; }
        public string TestRef_ReportedOn { get; set; }
        public Nullable<decimal> TestRef_TestId { get; set; }
        public string TestRef_UserInfo { get; set; }
    }
}
