//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Mst
    {
        public double TstMst_Key { get; set; }
        public string TstMst_name { get; set; }
        public Nullable<double> TstMst_TypeId { get; set; }
        public Nullable<double> TstMst_Rate { get; set; }
        public Nullable<double> TstMst_DeptId { get; set; }
        public Nullable<double> TstMst_MthdId { get; set; }
        public Nullable<double> TstMst_UnitId { get; set; }
        public Nullable<int> TstMst_RefNo { get; set; }
        public string TstMst_Rfrncerng { get; set; }
        public string TstMst_OthComment { get; set; }
        public Nullable<int> TstMst_PrntCmnTch { get; set; }
        public Nullable<int> TstMst_IsAvoid { get; set; }
        public Nullable<double> TstMst_CalcType { get; set; }
        public Nullable<double> TstMst_OrderBy { get; set; }
        public Nullable<int> TstMst_DispHead { get; set; }
        public Nullable<double> TstMst_DivsnId { get; set; }
        public Nullable<int> TstMst_TechId { get; set; }
        public string tst_RptDay { get; set; }
        public string tst_RptTmeDays { get; set; }
        public string tst_SmplType { get; set; }
        public string TstMst_Sample { get; set; }
        public string TstMst_Volume { get; set; }
        public string TstMst_CutOftime { get; set; }
        public string TstMst_TstMode { get; set; }
        public string TstMst_ShortName { get; set; }
        public Nullable<decimal> tst_SmplTypeId { get; set; }
        public Nullable<decimal> TstMst_DiscPer { get; set; }
        public string TstMst_EditedUsr { get; set; }
        public Nullable<decimal> TstMst_PerformId { get; set; }
        public string TstMst_IntrNote { get; set; }
        public Nullable<bool> TstMst_IsNABL { get; set; }
        public Nullable<bool> TstMst_IsSendSms { get; set; }
        public string TstMst_SpeciGender { get; set; }
        public string TstMst_SpeciTwo { get; set; }
        public Nullable<bool> TstMst_SmplBrCode { get; set; }
        public Nullable<bool> TstMst_RateFree { get; set; }
        public Nullable<bool> TstMst_AvdIncen { get; set; }
        public Nullable<bool> TstMst_AlphNmCrit { get; set; }
        public Nullable<int> TstMst_IsCovidTst { get; set; }
        public Nullable<int> TstMst_IsnewData { get; set; }
        public Nullable<int> TstMst_IsEditData { get; set; }
    }
}
