//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Order
    {
        public decimal TstOrdr_key { get; set; }
        public string TstOrdr_SampleId { get; set; }
        public string TstOrdr_TestCode { get; set; }
        public string TstOrdr_PName { get; set; }
        public string TstOrdr_Pcode { get; set; }
        public int TstOrdr_FluidType { get; set; }
        public string TstOrdr_Gender { get; set; }
        public Nullable<int> TstOrdr_Age { get; set; }
        public string TstOrdr_Ymd { get; set; }
        public Nullable<System.DateTime> TstOrdr_DateTime { get; set; }
        public string TstOrdr_UserInfo { get; set; }
        public Nullable<int> TstOrdr_IsOrdrd { get; set; }
        public Nullable<int> TstOrdr_BrId { get; set; }
        public Nullable<int> TstOrdr_YrId { get; set; }
        public Nullable<int> TstOrdr_CpyId { get; set; }
        public Nullable<decimal> TstOrdr_TestPerformAt { get; set; }
        public Nullable<decimal> TstOrdr_InvNo { get; set; }
        public Nullable<decimal> TstOrdr_Uptd { get; set; }
    }
}
