//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISFYPlatinumInvRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public double vchr_Key { get; set; }
        public Nullable<System.DateTime> vchr_Date { get; set; }
        public Nullable<double> vchr_BookId { get; set; }
        public Nullable<double> vchr_Id { get; set; }
        public string vchr_TransType { get; set; }
        public Nullable<double> vchr_TransNo { get; set; }
        public string vchr_Narration { get; set; }
        public Nullable<double> vchr_Payment { get; set; }
        public Nullable<double> vchr_Receipt { get; set; }
        public Nullable<int> vchr_Chq { get; set; }
        public string vchr_ChqNo { get; set; }
        public Nullable<System.DateTime> vchr_IssueDate { get; set; }
        public Nullable<System.DateTime> vchr_ChqDate { get; set; }
        public Nullable<int> vchr_ChqPassed { get; set; }
        public Nullable<double> vchr_Paid { get; set; }
        public Nullable<double> vchr_CurBal { get; set; }
        public string vchr_TimeStamp { get; set; }
        public Nullable<decimal> vchr_UsrId { get; set; }
        public Nullable<decimal> vchr_YrId { get; set; }
        public Nullable<decimal> vchr_CpyId { get; set; }
        public Nullable<decimal> vchr_Updtd { get; set; }
        public Nullable<int> vchr_BrId { get; set; }
        public Nullable<int> vchr_CashAllUsr { get; set; }
        public Nullable<int> vchr_CashUsr { get; set; }
        public Nullable<double> vchr_TdsAmt { get; set; }
        public byte[] vchr_Attachment { get; set; }
        public Nullable<decimal> vchr_AutoBrKey { get; set; }
        public Nullable<decimal> vchr_AutoBrVchrKey { get; set; }
    }
}
